package com.chinagps.fee.entity.po;

// Generated 2014-5-20 11:28:49 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TFeeAnswer generated by hbm2java
 */
public class Answer implements java.io.Serializable {

	private Long id;
	private Long paymentId;
	private Long answerId;
	private Float equipfee;
	private Float homefee;
	private Float laborcosts;
	private Float installationfee;
	private Long userId;
	private Date stamp;
	private String remark;

	public Answer() {
	}

	public Answer(Long id, Date stamp) {
		this.id = id;
		this.stamp = stamp;
	}

	public Answer(Long id, Long paymentId, Long answerId, Float equipfee,
			Float homefee, Float laborcosts, Float installationfee,
			Long userId, Date stamp, String remark) {
		this.id = id;
		this.paymentId = paymentId;
		this.answerId = answerId;
		this.equipfee = equipfee;
		this.homefee = homefee;
		this.laborcosts = laborcosts;
		this.installationfee = installationfee;
		this.userId = userId;
		this.stamp = stamp;
		this.remark = remark;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Long paymentId) {
		this.paymentId = paymentId;
	}

	public Long getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(Long answerId) {
		this.answerId = answerId;
	}

	public Float getEquipfee() {
		return this.equipfee;
	}

	public void setEquipfee(Float equipfee) {
		this.equipfee = equipfee;
	}

	public Float getHomefee() {
		return this.homefee;
	}

	public void setHomefee(Float homefee) {
		this.homefee = homefee;
	}

	public Float getLaborcosts() {
		return this.laborcosts;
	}

	public void setLaborcosts(Float laborcosts) {
		this.laborcosts = laborcosts;
	}

	public Float getInstallationfee() {
		return this.installationfee;
	}

	public void setInstallationfee(Float installationfee) {
		this.installationfee = installationfee;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Date getStamp() {
		return this.stamp;
	}

	public void setStamp(Date stamp) {
		this.stamp = stamp;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
