package com.chinagps.fee.entity.po;

// Generated 2014-5-20 11:28:49 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TFeeRefund generated by hbm2java
 */
public class Refund implements java.io.Serializable {

	private Long id;
	private Long subcoNo;
	private Long customerId;
	private Long orgId;
	private Float shallRetire;
	private Float realRetreat;
	private String listno;
	private Integer mode;
	private String person;
	private Date time;
	private Long opId;
	private Date stamp;
	private String remark;

	public Refund() {
	}

	public Refund(Long id, Date stamp) {
		this.id = id;
		this.stamp = stamp;
	}

	public Refund(Long id, Long subcoNo, Long customerId, Long orgId,
			Float shallRetire, Float realRetreat, String listno, Integer mode,
			String person, Date time, Long opId, Date stamp, String remark) {
		this.id = id;
		this.subcoNo = subcoNo;
		this.customerId = customerId;
		this.orgId = orgId;
		this.shallRetire = shallRetire;
		this.realRetreat = realRetreat;
		this.listno = listno;
		this.mode = mode;
		this.person = person;
		this.time = time;
		this.opId = opId;
		this.stamp = stamp;
		this.remark = remark;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getSubcoNo() {
		return this.subcoNo;
	}

	public void setSubcoNo(Long subcoNo) {
		this.subcoNo = subcoNo;
	}

	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	public Long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	public Float getShallRetire() {
		return this.shallRetire;
	}

	public void setShallRetire(Float shallRetire) {
		this.shallRetire = shallRetire;
	}

	public Float getRealRetreat() {
		return this.realRetreat;
	}

	public void setRealRetreat(Float realRetreat) {
		this.realRetreat = realRetreat;
	}

	public String getListno() {
		return this.listno;
	}

	public void setListno(String listno) {
		this.listno = listno;
	}

	public Integer getMode() {
		return this.mode;
	}

	public void setMode(Integer mode) {
		this.mode = mode;
	}

	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Long getOpId() {
		return this.opId;
	}

	public void setOpId(Long opId) {
		this.opId = opId;
	}

	public Date getStamp() {
		return this.stamp;
	}

	public void setStamp(Date stamp) {
		this.stamp = stamp;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
