package com.chinagps.fee.entity.po;

// Generated 2014-5-20 11:28:49 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TFeeBalance generated by hbm2java
 */
public class Balance implements java.io.Serializable {

	private Long balanceId;
	private Long subcoNo;
	private Long customerId;
	private Float balance;
	private Date stamp;

	public Balance() {
	}

	public Balance(Date stamp) {
		this.stamp = stamp;
	}

	public Balance(Long subcoNo, Long customerId, Float balance, Date stamp) {
		this.subcoNo = subcoNo;
		this.customerId = customerId;
		this.balance = balance;
		this.stamp = stamp;
	}

	public Long getBalanceId() {
		return this.balanceId;
	}

	public void setBalanceId(Long balanceId) {
		this.balanceId = balanceId;
	}

	public Long getSubcoNo() {
		return this.subcoNo;
	}

	public void setSubcoNo(Long subcoNo) {
		this.subcoNo = subcoNo;
	}

	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	public Float getBalance() {
		return this.balance;
	}

	public void setBalance(Float balance) {
		this.balance = balance;
	}

	public Date getStamp() {
		return this.stamp;
	}

	public void setStamp(Date stamp) {
		this.stamp = stamp;
	}

}
