package com.chinagps.fee.entity.po;

// Generated 2014-5-20 11:28:49 by Hibernate Tools 4.0.0

/**
 * TFeeRefundDetails generated by hbm2java
 */
public class RefundDetails implements java.io.Serializable {

	private Long id;
	private Long refundId;
	private String name;
	private Float fee;

	public RefundDetails() {
	}

	public RefundDetails(Long id) {
		this.id = id;
	}

	public RefundDetails(Long id, Long refundId, String name, Float fee) {
		this.id = id;
		this.refundId = refundId;
		this.name = name;
		this.fee = fee;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getRefundId() {
		return this.refundId;
	}

	public void setRefundId(Long refundId) {
		this.refundId = refundId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getFee() {
		return this.fee;
	}

	public void setFee(Float fee) {
		this.fee = fee;
	}

}
